Frederico Armando Machava

# Practical_6: Numpy

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [50]:
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [64]:
a = np.array([[0,0,0], [0,0,0], [0,0,0]])
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [84]:
import numpy as np
a = np.linspace(0, 5, 10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [88]:
d = np.eye(5)         
print(d)  

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [96]:
f = np.random.random((4,4)) 
print(f) 

[[0.971945   0.87819347 0.50962438 0.05571469]
 [0.45115921 0.01998767 0.44171092 0.97958673]
 [0.35944446 0.48089353 0.68866118 0.88047589]
 [0.91823547 0.21682214 0.56518887 0.86510256]]


### Exercise 6:
Find the shape of a NumPy array.

In [105]:
import numpy as np
print(np.shape)

<function shape at 0x000002BA41785580>


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [110]:
a = np.arange(1, 17).reshape((4, 4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

In [112]:
import numpy as np
print(np.dtype)

<class 'numpy.dtype'>


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [129]:
import numpy as np
a = np.arange(1, 101)
b = a[a % 2 == 0]
print(b)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [165]:
import numpy as np
np.random.randint(10, 50, size=(6,6))
# a = np.(10, 51)
# .reshape((6, 6))
# random.random((6, 6))
# b = a[a % 2 == 0]
# c = a.random.random((10, 51))
# print(len(a))

array([[37, 24, 11, 46, 20, 32],
       [21, 12, 26, 42, 10, 48],
       [29, 23, 40, 34, 12, 13],
       [40, 44, 23, 18, 29, 41],
       [18, 36, 12, 13, 24, 42],
       [14, 13, 21, 32, 23, 21]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [172]:
a = np.arange(2)
b = a[:0]
print(b)

[]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [180]:
x = np.array(0)
y = np.array(0)

print(np.add(x, y))

0


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [208]:
x = np.arange(1, 6)
y = np.mean(x)
z = np.median(x)
h = np.std(x)
print(y) 
print(z)     
print(h)     

3.0
3.0
1.4142135623730951


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [211]:
t = np.array([4, 5, 6])
x = np.max(t)
y = np.min(t)
print(x)
print(y)

6
4


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [224]:
x = np.random.randint(-10, 10, size=(20,))
print(x)
y = np.argmax(x)
print(y)

3


### Exercise 16:
Create a NumPy array and reverse its elements.

In [226]:
t = np.array([4, 5, 6])
x = np.flip(t)
print(x)

[6 5 4]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [232]:
a = np.array([[1,2,3], [5,6,7], [9,10,11]])
b = np.array([[3,2,1], [7,6,5], [11,10,12]])
print(a*b)

[[  3   4   3]
 [ 35  36  35]
 [ 99 100 132]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [234]:
t = np.array([4, 5, 6])
x = np.diag(t)
print(x)

[[4 0 0]
 [0 5 0]
 [0 0 6]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [236]:
a = np.array([[1,2,3], [5,6,7]])
b = np.array([[3,2,1], [7,6,5]])
print(a*b)

[[ 3  4  3]
 [35 36 35]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [240]:
a = np.array([[1,2,3], [5,6,7]])
x = a.flatten()
print(x)

[1 2 3 5 6 7]


### Exercise 21:
Stack two NumPy arrays vertically.

In [246]:
a = np.array([1,2,3])
b = np.array([3,2,1])
x = np.vstack((a,b))
print(x)

[[1 2 3]
 [3 2 1]]


### Exercise 22:
Stack two NumPy arrays horizontally.

In [248]:
a = np.array([1,2,3])
b = np.array([3,2,1])
x = np.hstack((a,b))
print(x)

[1 2 3 3 2 1]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [264]:
x = np.array([1,2,3,4,5,6])
y = np.split(x, 6, axis=0)
print(y)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [270]:
f = np.random.random((4,4)) 
print(f) 
g = np.round(f, 2)
print(g)

[[0.48805628 0.35561274 0.94043195 0.76532525]
 [0.74866362 0.90371974 0.08342244 0.55219247]
 [0.58447607 0.96193638 0.29214753 0.24082878]
 [0.10029394 0.01642963 0.92952932 0.66991655]]
[[0.49 0.36 0.94 0.77]
 [0.75 0.9  0.08 0.55]
 [0.58 0.96 0.29 0.24]
 [0.1  0.02 0.93 0.67]]


### Exercise 25:
Find the unique elements of a NumPy array.

In [274]:
x = np.array([1,2,2,3,5,3,4,5,6])
y = np.unique(x)
print(y)

[1 2 3 4 5 6]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [278]:
x = np.array([1,2,2,3,5,3,4,5,6])
y = np.where(x<5, 5,x)
print(y)

[5 5 5 5 5 5 5 5 6]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [282]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.cumsum(x)) 

[ 1  3  6 10]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [286]:
import numpy as np


y = np.array([1, 0, 2, 0, 3, 4, 0, 5])


non_zero_count = np.count_nonzero(y)


print(y)
print(f"Number of non-zero elements: {non_zero_count}")



[1 0 2 0 3 4 0 5]
Number of non-zero elements: 5


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [290]:
x = np.array([1,2,10,7,35,3,4,0,-6,11,-8])
y = np.sort(x)
print(y)

[-8 -6  0  1  2  3  4  7 10 11 35]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [298]:
a = np.array([[1,2,3], [5,6,7], [9,10,11]])
row_wise = np.sum(a, axis=1)
print(row_wise)
column_wise = np.sum(a, axis=0)
print(column_wise)

[ 6 18 30]
[15 18 21]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [302]:
a = np.array([[1,2,3], [4,5,6]])
a_min = np.min(a)
a_max = np.max(a)
a_ram = (a-a_min)/(a_max-a_min)
print(a_ram)


[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

In [308]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a, b))

32


In [316]:
a = np.array([[1,2], [0,2]])
b = np.array([[4,5], [2,0]])
print(np.dot(a, b))

[[8 5]
 [4 0]]


### Exercise 33:
Find the trace of a square NumPy matrix.

In [312]:
a = np.array([[1,2], [3,4]])
trace = np.trace(a)
print(trace)

5


### Exercise 34:
Create a 2D array and swap two rows.

In [322]:
a = np.array([[1,2], [0,2]])
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[1 2]
 [0 2]]
[[0 2]
 [1 2]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [332]:
x = np.array([1,2,10,7,35,3,4,0,-6,11,-8])
column_x = x[:, None]
print(column_x)

[[ 1]
 [ 2]
 [10]
 [ 7]
 [35]
 [ 3]
 [ 4]
 [ 0]
 [-6]
 [11]
 [-8]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

In [356]:
a = np.array([[1,0,0], [1,1,1], [1,0,1]])
determinant = np.linalg.det(a)
print(determinant)

1.0


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [344]:
import numpy as np


matrix = np.array([[4, 2],
                   [1, 3]])


eigenvalues, eigenvectors = np.linalg.eig(matrix)


print("Matrix:")
print(matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Matrix:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Exercise 38:
Solve a system of linear equations using NumPy.

In [352]:
import numpy as np


A = np.array([[2, 3],
              [4, 1]])


b = np.array([5, 11])


solution = np.linalg.solve(A, b)


print("Solution:")
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")


Solution:
x = 2.8
y = -0.2


### Exercise 39:
Add Gaussian noise to a NumPy array.

In [360]:
x = np.random.randint(1, 11, size=(5,5))
y = 3
gaussian_y = np.random.normal(scale=y, size=x.shape)
z = x + gaussian_y 
print(z)

[[ 7.13609837  4.25358517  1.83473726  6.84620966  4.3170458 ]
 [10.51493235  0.75106356  8.07078378  2.40702169  2.96886304]
 [ 7.03369998  4.81561604  6.3482943   9.59005027  4.31214063]
 [ 2.97405624  9.01697529  8.50920259  4.01664763  5.72405747]
 [13.67004012  3.74324496  0.77084925  8.34912362  5.2470621 ]]


### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [362]:
a = np.array([[1,0,0,1], [1,1,1,2], [1,0,1,2], [1,2,3,4]])
diagonal = np.diag(a)
print(diagonal)

[1 1 1 4]
